export default {
  'img[alt]': ['QW-BP2'],
  table: ['QW-BP9', 'QW-BP12'],
  'table table': ['QW-BP5'],
  ':not(svg) > title': ['QW-BP6', 'QW-BP7'],
  'h1, h2, h3, h4, h5, h6, [role="heading"]': ['QW-BP8'],
  'basefont, big, blink, center, font, marquee, multicol, nobr, spacer, tt': ['QW-BP10'],
  'body, body *': ['QW-BP11'],
  body: ['QW-BP1', 'QW-BP20', 'QW-BP21', 'QW-BP22', 'QW-BP28'],
  'a > img': ['QW-BP13'],
  'a:first-child': ['QW-BP4'],
  '[width]:not(img)': ['QW-BP15'],
  'a[href]': ['QW-BP17'],
  'style, [style]': ['QW-BP18'],
  'header:not([role]), [role=banner]': ['QW-BP19'],
  li: ['QW-BP23'],
  'ul, ol,menu': ['QW-BP24'],
  'aside:not([role]), [role=complementary]': ['QW-BP25'],
  'footer:not([role]), [role=contentinfo]': ['QW-BP26'],
  'main:not([role]), [role=main]': ['QW-BP27']
};
