const typesWithLabel = ['text', 'password', 'search', 'tel', 'email', 'url'];
const tabularElements = ['tr', 'td', 'th'];
const formElements = ['form', 'select', 'option', 'datalist', 'optgroup', 'input'];
const sectionAndGrouping = [
  'span',
  'article',
  'section',
  'nav',
  'aside',
  'hgroup',
  'header',
  'footer',
  'address',
  'p',
  'hr',
  'blockquote',
  'div',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'li',
  'ul',
  'ol',
  'dd',
  'dt',
  'dl',
  'figcaption'
];
const controlRoles = [
  'textbox',
  //'menubutton',
  'combobox',
  'listbox',
  'range',
  'progressbar',
  'scrollbar',
  'slider',
  'spinbutton'
];
const widgetElements = [
  'a',
  'button',
  'input',
  'meter',
  'output',
  'progress',
  'select',
  'td',
  'textarea',
  'li',
  'option'
];

// Concrete roles whose WAI-ARIA taxonomy includes `widget`. This is a semantic
// role list, not a list of elements that merely support `aria-disabled`.
// In particular, separator and tabpanel are not widget subclasses.
const widgetRoles = [
  'button',
  'checkbox',
  'columnheader',
  'combobox',
  'doc-backlink',
  'doc-biblioref',
  'doc-glossref',
  'doc-noteref',
  'grid',
  'gridcell',
  'link',
  'listbox',
  'menu',
  'menubar',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'progressbar',
  'radio',
  'radiogroup',
  'row',
  'rowheader',
  'scrollbar',
  'searchbox',
  'slider',
  'spinbutton',
  'switch',
  'tab',
  'tablist',
  'textbox',
  'tree',
  'treegrid',
  'treeitem'
];

// Concrete WAI-ARIA roles whose superclass chain includes `group` or `widget`.
// R37 uses this broader list because ACT excludes text inside disabled groups
// as well as disabled widgets. Extension roles are included where their own
// specifications inherit from one of those core roles.
const groupOrWidgetRoles = [
  'group',
  'button',
  'checkbox',
  'columnheader',
  'combobox',
  'doc-backlink',
  'doc-biblioref',
  'doc-glossref',
  'doc-noteref',
  'graphics-object',
  'grid',
  'gridcell',
  'link',
  'listbox',
  'menu',
  'menubar',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'progressbar',
  'radio',
  'radiogroup',
  'row',
  'rowheader',
  'scrollbar',
  'searchbox',
  'slider',
  'spinbutton',
  'switch',
  'tab',
  'tablist',
  'textbox',
  'toolbar',
  'tree',
  'treegrid',
  'treeitem'
];

// Abstract roles cannot be used as explicit semantic roles. Keeping this list
// separate lets role-token fallback skip them without changing the existing
// role metadata representation.
const abstractRoles = [
  'command',
  'composite',
  'input',
  'landmark',
  'range',
  'roletype',
  'section',
  'sectionhead',
  'select',
  'structure',
  'widget',
  'window'
];

// Concrete roles defined by the DPUB-ARIA and Graphics-ARIA modules. They are
// valid role tokens even though the legacy core role metadata does not contain
// entries for them.
const extensionRoles = [
  'doc-abstract',
  'doc-acknowledgments',
  'doc-afterword',
  'doc-appendix',
  'doc-backlink',
  'doc-biblioentry',
  'doc-bibliography',
  'doc-biblioref',
  'doc-chapter',
  'doc-colophon',
  'doc-conclusion',
  'doc-cover',
  'doc-credit',
  'doc-credits',
  'doc-dedication',
  'doc-endnote',
  'doc-endnotes',
  'doc-epigraph',
  'doc-epilogue',
  'doc-errata',
  'doc-example',
  'doc-footnote',
  'doc-foreword',
  'doc-glossary',
  'doc-glossref',
  'doc-index',
  'doc-introduction',
  'doc-noteref',
  'doc-notice',
  'doc-pagebreak',
  'doc-pagelist',
  'doc-part',
  'doc-preface',
  'doc-prologue',
  'doc-pullquote',
  'doc-qna',
  'doc-subtitle',
  'doc-tip',
  'doc-toc',
  'graphics-document',
  'graphics-object',
  'graphics-symbol'
];
const nameFromContentElements = [
  'button',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'a',
  'link',
  'option',
  'output',
  'summary',
  'abbr',
  'b',
  'bdi',
  'bdo',
  'br',
  'caption',
  'cite',
  'code',
  'dfn',
  'em',
  'i',
  'kbd',
  'mark',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'small',
  'strong',
  'sub',
  'and',
  'sup',
  'time',
  'u',
  'var',
  'wbr',
  'label'
];
const nameFromContentRoles = [
  'button',
  'caption',
  'cell',
  'checkbox',
  'columnheader',
  'gridcell',
  'heading',
  'link',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'radio',
  'row',
  'rowgroup',
  'rowheader',
  'switch',
  'tab',
  'tooltip',
  'tree',
  'treeitem'
];
const noAccessibleObjectOrChild = ['clipPath', 'cursor', 'defs', 'desc', 'metadata', 'pattern'];
const noAccessibleObject = [
  'animate',
  'animateMotion',
  'animateTransform',
  'discard',
  'filter',
  'hatch',
  'hatchPath',
  'linearGradient',
  'marker',
  'mask',
  'meshPatch',
  'meshRow',
  'mpath',
  'radialGradient',
  'script',
  'set',
  'solidColor',
  'stop',
  'style',
  'switch',
  'view',
  'title'
];
const elementsLikeHtml = ['canvas', 'iframe', 'source', 'track', 'video'];
const childPresentationalRole = [
  'button',
  'checkbox',
  'img',
  'math',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'progressbar',
  'radio',
  'scrollbar',
  'separator',
  'slider',
  'switch',
  'tab'
];
const textContainer = ['textPath', 'text', 'tspan'];
const notDefaultAT = [
  'b',
  'bdi',
  'bdo',
  'br',
  'cite',
  'col',
  'colgroup',
  'data',
  'dfn',
  'em',
  'kbd',
  'link',
  'map',
  'meta',
  'span',
  'noscript',
  'script',
  'param',
  'picture',
  'q',
  's',
  'samp',
  'small',
  'source',
  'strong',
  'style',
  'sub',
  'sup',
  'tbody',
  'thead',
  'tfoot',
  'template',
  'title',
  'track',
  'u',
  'var',
  'wbr'
];
const notExposedIfEmpty = ['div', 'p', 'pre'];
const needsToBeInsideDetails = ['summary'];

export {
  notDefaultAT,
  notExposedIfEmpty,
  textContainer,
  needsToBeInsideDetails,
  childPresentationalRole,
  elementsLikeHtml,
  noAccessibleObjectOrChild,
  noAccessibleObject,
  typesWithLabel,
  tabularElements,
  formElements,
  sectionAndGrouping,
  controlRoles,
  widgetElements,
  widgetRoles,
  groupOrWidgetRoles,
  abstractRoles,
  extensionRoles,
  nameFromContentElements,
  nameFromContentRoles
};
